server:
  port: 9000

services:
  url:
    admintool-core: http://localhost:8081
    admintool-frontend: http://localhost:5174
spring:
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 655460
